-- Insertar valores iniciales en la tabla Productos si no existen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM Productos) THEN
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre XXS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer XXS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer XXS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer XXS', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre XXS', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer XXS', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre XXS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre XXS', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer XXS', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre XXS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer XXS', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre XXS', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer XXS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre XXS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre XXS', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer XXS', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre XXS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer XXS', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre XXS', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer XXS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre XXS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer XXS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre XXS', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer XXS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer XXS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre XXS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre XXS', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer XXS', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre XXS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer XXS', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre XXS', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer XXS', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre XXS', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer XXS', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre XXS', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer XXS', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre XXS', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer XXS', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre XXS', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer XXS', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello XXS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas XXS', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador XXS', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche XXS', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos XXS', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB XXS', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil XXS', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico XXS', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico XXS', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas XXS', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional XXS', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina XXS', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio XXS', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio XXS', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth XXS', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente XXS', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital XXS', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB XXS', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop XXS', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera XXS', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XXS', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica XXS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD XXS', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil XXS', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas XXS', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad XXS', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal XXS', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre XXS', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas XXS', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil XXS', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa XXS', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora XXS', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador XXS', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa XXS', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa XXS', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol XXS', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta XXS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde XXS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla XXS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo XXS', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga XXS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables XXS', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio XXS', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma XXS', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia XXS', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña XXS', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir XXS', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo XXS', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED XXS', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo XXS', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula XXS', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua XXS', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable XXS', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable XXS', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul XXS', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre XS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer XS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer XS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer XS', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre XS', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer XS', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre XS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre XS', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer XS', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre XS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer XS', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre XS', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer XS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre XS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre XS', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer XS', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre XS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer XS', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre XS', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer XS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre XS', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer XS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre XS', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer XS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer XS', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre XS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre XS', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer XS', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre XS', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer XS', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre XS', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer XS', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre XS', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer XS', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre XS', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer XS', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre XS', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer XS', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre XS', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer XS', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello XS', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas XS', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador XS', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche XS', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos XS', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB XS', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil XS', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico XS', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico XS', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas XS', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional XS', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina XS', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio XS', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio XS', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth XS', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente XS', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital XS', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB XS', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop XS', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera XS', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XS', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica XS', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD XS', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil XS', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas XS', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad XS', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal XS', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre XS', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas XS', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil XS', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa XS', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora XS', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador XS', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa XS', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa XS', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol XS', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta XS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde XS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla XS', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo XS', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga XS', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables XS', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio XS', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma XS', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia XS', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña XS', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir XS', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo XS', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED XS', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo XS', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula XS', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua XS', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable XS', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable XS', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul XS', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre S', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer S', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer S', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer S', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre S', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer S', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre S', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre S', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer S', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre S', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer S', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre S', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer S', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre S', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre S', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer S', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre S', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer S', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre S', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer S', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre S', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer S', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre S', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer S', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer S', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre S', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre S', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer S', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre S', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer S', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre S', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer S', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre S', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer S', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre S', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer S', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre S', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer S', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre S', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer S', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello S', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas S', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador S', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche S', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos S', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB S', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil S', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico S', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico S', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas S', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional S', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina S', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio S', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio S', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth S', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente S', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital S', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB S', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop S', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera S', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora S', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica S', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD S', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil S', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas S', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad S', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal S', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre S', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas S', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil S', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa S', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora S', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador S', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa S', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa S', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol S', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta S', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde S', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla S', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo S', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga S', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables S', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio S', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma S', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia S', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña S', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir S', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo S', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED S', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo S', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula S', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua S', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable S', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable S', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul S', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre M', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer M', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer M', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer M', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre M', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer M', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre M', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre M', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer M', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre M', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer M', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre M', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer M', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre M', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre M', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer M', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre M', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer M', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre M', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer M', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre M', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer M', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre M', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer M', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer M', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre M', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre M', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer M', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre M', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer M', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre M', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer M', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre M', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer M', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre M', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer M', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre M', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer M', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre M', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer M', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello M', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas M', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador M', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche M', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos M', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB M', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil M', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico M', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico M', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas M', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional M', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina M', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio M', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio M', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth M', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente M', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital M', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB M', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop M', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera M', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora M', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica M', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD M', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil M', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas M', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad M', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal M', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre M', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas M', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil M', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa M', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora M', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador M', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa M', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa M', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol M', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta M', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde M', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla M', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo M', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga M', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables M', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio M', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma M', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia M', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña M', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir M', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo M', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED M', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo M', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula M', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua M', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable M', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable M', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul M', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre L', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer L', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer L', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer L', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre L', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer L', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre L', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre L', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer L', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre L', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer L', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre L', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer L', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre L', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre L', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer L', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre L', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer L', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre L', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer L', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre L', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer L', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre L', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer L', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer L', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre L', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre L', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer L', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre L', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer L', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre L', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer L', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre L', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer L', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre L', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer L', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre L', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer L', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre L', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer L', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello L', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas L', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador L', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche L', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos L', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB L', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil L', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico L', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico L', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas L', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional L', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina L', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio L', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio L', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth L', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente L', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital L', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB L', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop L', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera L', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora L', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica L', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD L', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil L', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas L', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad L', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal L', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre L', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas L', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil L', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa L', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora L', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador L', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa L', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa L', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol L', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta L', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde L', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla L', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo L', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga L', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables L', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio L', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma L', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia L', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña L', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir L', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo L', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED L', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo L', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula L', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua L', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable L', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable L', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul L', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre XL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer XL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer XL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer XL', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre XL', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer XL', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre XL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre XL', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer XL', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre XL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer XL', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre XL', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer XL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre XL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre XL', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer XL', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre XL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer XL', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre XL', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer XL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre XL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer XL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre XL', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer XL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer XL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre XL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre XL', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer XL', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre XL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer XL', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre XL', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer XL', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre XL', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer XL', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre XL', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer XL', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre XL', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer XL', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre XL', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer XL', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello XL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas XL', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador XL', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche XL', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos XL', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB XL', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil XL', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico XL', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico XL', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas XL', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional XL', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina XL', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio XL', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio XL', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth XL', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente XL', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital XL', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB XL', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop XL', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera XL', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XL', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica XL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD XL', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil XL', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas XL', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad XL', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal XL', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre XL', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas XL', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil XL', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa XL', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora XL', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador XL', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa XL', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa XL', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol XL', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta XL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde XL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla XL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo XL', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga XL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables XL', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio XL', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma XL', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia XL', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña XL', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir XL', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo XL', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED XL', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo XL', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula XL', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua XL', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable XL', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable XL', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul XL', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camisa de Hombre XXL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Hombre XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vestido de Mujer XXL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Blusa de Mujer XXL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalón de Mujer XXL', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Hombre XXL', 44.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatos de Mujer XXL', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sudadera de Hombre XXL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Hombre XXL', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta de Mujer XXL', 69.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Hombre XXL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pijama de Mujer XXL', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Hombre XXL', 14.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camiseta de Mujer XXL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Falda de Mujer XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Hombre XXL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Suéter de Mujer XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Hombre XXL', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrigo de Mujer XXL', 99.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Hombre XXL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Zapatillas de Deporte de Mujer XXL', 54.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Hombre XXL', 34.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sandalias de Mujer XXL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cinturón de Hombre XXL', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bufanda de Mujer XXL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Hombre XXL', 22.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sombrero de Mujer XXL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolso de Mujer XXL', 49.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Hombre XXL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Hombre XXL', 9.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Calcetines de Mujer XXL', 11.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Hombre XXL', 15.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Guantes de Invierno de Mujer XXL', 17.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Hombre XXL', 55.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Perfume de Mujer XXL', 59.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Hombre XXL', 75.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Mujer XXL', 79.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colonia de Hombre XXL', 35.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mascarilla Facial de Mujer XXL', 10.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Champú de Hombre XXL', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Acondicionador de Cabello de Mujer XXL', 8.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gel de Ducha de Hombre XXL', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Jabón Líquido de Mujer XXL', 6.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha para el Cabello XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secador de Cabello XXL', 24.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas XXL', 89.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Refrigerador XXL', 499.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche XXL', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos XXL', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB XXL', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil XXL', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico XXL', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico XXL', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas XXL', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional XXL', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Silla de Oficina XXL', 149.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio XXL', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Organizador de Escritorio XXL', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth XXL', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente XXL', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital XXL', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB XXL', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila para Laptop XXL', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera XXL', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora XXL', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica XXL', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD XXL', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil XXL', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Ollas XXL', 119.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad XXL', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal XXL', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre XXL', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas XXL', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil XXL', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa XXL', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora XXL', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador XXL', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa XXL', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Toalla de Playa XXL', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Sol XXL', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta XXL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Verde XXL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta Amarilla XXL', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Casco de Ciclismo XXL', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Colchoneta de Yoga XXL', 29.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables XXL', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio XXL', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma XXL', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Correa de Resistencia XXL', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tienda de Campaña XXL', 79.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Saco de Dormir XXL', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila de Senderismo XXL', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED XXL', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bastón de Senderismo XXL', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brújula XXL', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Botella de Agua XXL', 14.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Chaqueta Impermeable XXL', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Plegable XXL', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Paraguas Azul XXL', 12.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartphone 128GB', 299.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Computadora Portátil', 799.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mouse Ergonómico', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Teclado Mecánico', 89.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor 24 pulgadas', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora Multifuncional', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Bluetooth', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj Inteligente', 99.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Digital', 249.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 64GB', 199.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Auriculares Inalámbricos', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lámpara de Escritorio', 39.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara de Seguridad', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Control Remoto Universal', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Ventilador de Torre', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de DVD', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parlante Portátil', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microondas', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aire Acondicionado Portátil', 299.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Plancha de Ropa', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Aspiradora', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Deshumidificador', 199.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Secadora de Ropa', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pesas Ajustables', 99.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bola de Ejercicio', 19.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rodillo de Espuma', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Linterna LED', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Drone con Cámara', 299.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Consola de Videojuegos', 499.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Disco Duro Externo 1TB', 99.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Memoria USB 64GB', 14.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Router WiFi', 129.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cable HDMI 2m', 9.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Adaptador USB-C', 29.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Kit de Herramientas para Electrónica', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lector de Tarjetas', 19.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smartwatch Infantil', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sistema de Alarma', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cargador Inalámbrico', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('MicroSD 128GB', 39.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Soporte para Laptop', 24.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet para Niños', 129.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Controlador MIDI', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Radio Digital', 39.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Batería Externa 10000mAh', 49.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Web HD', 79.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Micrófono de Condensador', 129.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pizarra Digital', 299.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monitor Curvo 27 pulgadas', 399.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Proyector Portátil', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Deportiva 4K', 149.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pulsera de Actividad', 49.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Soporte para Monitor', 29.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Enchufe Inteligente', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bombilla Inteligente', 39.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Termómetro Digital', 14.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Joystick para PC', 69.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Walkie Talkie', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Smart TV 50 pulgadas', 499.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pantalla Interactiva', 299.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Antena de TV Digital', 24.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sensores de Movimiento', 49.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tarjeta Gráfica 8GB', 399.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Estación de Carga USB', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Altavoz Inteligente', 99.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reproductor de MP3', 29.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tablet 256GB', 299.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Balanza Inteligente', 59.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Hub USB', 14.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Lector de E-Books', 129.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Impresora 3D', 699.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cámara Instantánea', 99.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microscopio Digital', 149.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Termostato Inteligente', 199.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Gafas de Realidad Virtual', 399.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Analizador de Redes', 129.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Interruptor WiFi', 24.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Router Malla', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Peluche', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Construcción', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeca', 24.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Robot Interactivo', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Camión de Bomberos', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Puzzle 500 Piezas', 14.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Mesa', 39.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Coche de Carreras', 29.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Plastilina', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Triciclo Infantil', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bicicleta para Niños', 79.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Helicóptero RC', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Patinete', 39.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Monopatín', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cubo de Rubik', 9.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Disfraz de Superhéroe', 24.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Cocina', 29.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Castillo de Juguete', 69.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete Didáctico', 24.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila Escolar', 19.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Herramientas', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Peluche Gigante', 59.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete Musical', 19.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pista de Coches', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Trenes', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Dron Infantil', 39.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Avión de Juguete', 19.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Estuche de Arte', 29.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeca Bailarina', 19.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Pintura', 24.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeca Princesa', 24.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bolsa de Juegos', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Dinosaurios', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Telescopio Infantil', 39.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Caja Registradora', 29.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Baño', 14.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Bloques de Madera', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Kit de Ciencia', 39.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Pesca', 14.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Estación de Bomberos', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rompecabezas 3D', 24.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Cartas', 9.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeca Parlante', 34.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Batidora de Juguete', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Bomberos', 14.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Té', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Circuito de Coches', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microscopio Infantil', 29.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Veterinario', 19.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeco de Acción', 34.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Madera', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Puzzle de Animales', 14.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Playa', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mundo Marino', 14.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Aventura', 24.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Caja de Juguetes', 19.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pista de Tren', 29.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tren de Madera', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Maletín de Juguetes', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Cocina', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Educativo', 39.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rompecabezas Diario', 14.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Muñeca Princesa', 39.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cubo de Actividades', 29.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cochecito de Bebé', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete Musical', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Avión de Madera', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tren Eléctrico', 69.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Circuito de Autobuses', 19.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Microscopio 3D', 29.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Cocina', 39.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mochila Escolar', 29.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Kit de Ciencia', 39.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Robot de Juguete', 49.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Veterinario', 24.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Peluche Gigante', 59.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Cartas', 19.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juguete de Dinosaurios', 24.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera', 79.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Licuadora', 89.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tetera Eléctrica', 39.99, 100);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tostadora', 29.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Horno Microondas', 199.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Batidora de Mano', 49.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Exprimidor de Cítricos', 24.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Olla de Presión', 99.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Sartenes', 79.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Batería de Cocina', 119.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cuchillos de Cocina', 29.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tabla de Cortar', 14.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Molinillo de Café', 49.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrelatas Eléctrico', 19.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Procesador de Alimentos', 129.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Freidora de Aire', 89.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Vaporera', 39.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Panificadora', 119.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cafetera Espresso', 139.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Hervidor Eléctrico', 24.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Picadora de Carne', 79.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Molde para Tartas', 14.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rallador de Queso', 9.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Termo de Café', 24.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cocina Portátil', 199.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Parrilla Eléctrica', 129.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Juego de Cucharas Medidoras', 9.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Termómetro de Cocina', 19.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Mezclador Eléctrico', 49.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Set de Recipientes', 29.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pelador de Patatas', 14.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tijeras de Cocina', 9.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Molde para Galletas', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Reloj de Cocina', 19.99, 60);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Sacacorchos', 14.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Abrebotellas', 4.99, 40);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Cesto de Frutas', 24.99, 50);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Tamiz para Harina', 9.99, 30);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Soplete de Cocina', 29.99, 70);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Dispensador de Agua', 39.99, 10);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Escurridor de Platos', 19.99, 90);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Brocha de Cocina', 9.99, 20);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Pinza para Ensalada', 14.99, 80);
        INSERT INTO Productos (nombre, precio, stock) VALUES ('Rallador de Verduras', 19.99, 50);
    END IF;
END
$$;